spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goodpang

    username: "root"
    password: "0000"
  mvc:
    hidden method:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10


  data:
    web:
      pageable:
        default-page-size : 9
  tymeleaf:
    prefix: classpath:/templates/
    suffix: .html


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.security: DEBUG
server:
  servlet:
    session:
      persistent : false
      timeout: 30m
      tracking-modes: cookie
